---
- name: Install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: yes
  become: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Add vagrant user to docker group
  user:
    name: vagrant
    group: docker
    append: yes
  become: yes

- name: Build and start MongoDB Docker container
  docker_container:
    name: mongodb-container
    image: mongo:latest
    state: started
    restart_policy: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - Gerrys_network
  become: yes

- name: Create Docker network
  docker_network:
    name: Gerrys_network
    state: present
  become: yes
