version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: gerrykiptoo/frontend:1.0.0
    ports:
      - "3000:3000"
      
    depends_on:
      - backend
    networks:
      - Gerrys_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gerrykiptoo/backend:1.0.0
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - Gerrys_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - Gerrys_network

volumes:
  mongo-data:

networks:
  Gerrys_network:
